First proof-of-concept of text flow into footer
brailleapps/dotify.api pull request #11
Opened 2016-12-13 09:14 UTC by bertfrees

See https://github.com/braillespecs/obfl/issues/60

2016-12-19 09:18 UTC, joeha480 requested changes
Could you please add javadoc to the class and public methods explaining the purpose and usage.

2016-12-19 19:21 UTC, bertfrees commented
Is this alright?

2016-12-20 07:17 UTC, joeha480 approved these changes
Looks good. Thanks!

2016-12-20 07:23 UTC, joeha480 commented
Merged in 0510f9c5b789eedcf256c12e40de03ea906fc725. Thanks!

2016-12-20 07:23 UTC, closed without merging